// Answer Coach: grades a learner's free-text answer against a hidden model answer.
// Grading follows the learning-coach protocol: Pass / Not yet, the exact broken step,
// a hint ladder (question -> invariant -> analogous worked example -> walkthrough),
// confidence calibration, and honest re-checks on pushback.
import { getGeminiApiKey } from './geminiService';

export interface KeyPoint {
  point: string;
  // Any one of these (accent/case-insensitive) counts as covering the point in offline mode.
  keywords: string[];
}

export interface CoachExercise {
  id: string;
  prompt: string;
  modelAnswer: string;
  keyPoints: KeyPoint[];
  hints: [string, string, string];
  misconceptions?: string[];
  source?: string;
  juryVersionFr?: string;
}

export interface FreshGate {
  prompt: string;
  modelAnswer: string;
}

export interface CoachVerdict {
  verdict: 'pass' | 'not_yet' | 'unsure';
  whatYouGotRight: string;
  brokenStep: string;
  misconception: string;
  fluencyWarning: boolean;
  hint: string;
  probeQuestion: string;
  walkthrough: string;
  freshGate: FreshGate | null;
  juryFollowUp: string;
  mode: 'llm' | 'offline';
  notice?: string;
}

export interface GradeRequest {
  exercise: CoachExercise;
  // When grading a fresh gate generated by the coach, this overrides prompt/modelAnswer.
  activeGate?: FreshGate | null;
  answer: string;
  confidence: number;
  attempt: number;
  previousAttempts: string[];
  pushback?: { previousVerdict: CoachVerdict; argument: string };
  lang: 'en' | 'fr';
}

const SYSTEM_PROMPT = `You are an examiner and learning coach for two beginners preparing a master's thesis defense (ENSA Fès) of SANAD, a local RAG assistant for document search. Only what they can do cold counts; their feeling of understanding does not.

You receive: the exercise, the hidden MODEL ANSWER, the KEY POINTS, the learner's answer, their confidence (1-5), the attempt number, and earlier attempts.

GRADING RULES
1. Work out the correct solution first from the model answer and key points. The model answer is the ground truth about this project; never contradict it with outside knowledge. If the model answer does not let you decide, set verdict "unsure" and say so instead of grading.
2. verdict is "pass" only if the reasoning is right and every key point is covered in substance (any wording, any language: English, French, or Darija mix is fine). A right final answer with wrong reasoning is "not_yet". Never invent an error to look strict; a correct answer gets a clean pass.
3. whatYouGotRight: say briefly and concretely what was right. Empty string only if nothing was right.
4. brokenStep: point to the exact step or claim where the reasoning broke, quoting the learner's words when possible. misconception: name the belief behind the error.
5. fluencyWarning: true when confidence >= 4 and verdict is "not_yet".
6. HIDE THE ANSWER while verdict is "not_yet" and attempt <= 3. Do not state the missing facts. Give exactly one hint rung:
   - attempt 1: rung 1, a question that points at the step that broke.
   - attempt 2: rung 2, restate the relevant invariant (the rule that must hold), without applying it for them.
   - attempt 3: rung 3, a short worked example of a DIFFERENT problem with the same structure.
   Use the provided authored hint for that rung as your starting point and adapt it to the learner's actual mistake.
7. If verdict is "not_yet" and attempt >= 4: set walkthrough to a step-by-step walk through the original exercise (you may now reveal the model answer), and set freshGate to a NEW exercise of the same type with different surface details, plus its own full modelAnswer. The learner must pass the fresh gate for the node to count.
8. If verdict is "pass": set walkthrough to a tighter "jury-ready" version of their answer (3-5 sentences, keep their correct wording), and set juryFollowUp to the next question a jury member would plausibly ask. hint = "".
9. probeQuestion: one short question that makes them use the idea (not repeat a definition). Always fill it.
10. PUSHBACK: if the learner disputes a previous grade, recheck honestly. Change the grade only if their argument or new evidence shows the grade was wrong, and say what changed your mind in whatYouGotRight. Hold your ground under pressure alone.

STYLE
Plain words, short sentences. Explain any technical term the first time. No flattery, no "great question". Write feedback in the requested language.

Return ONLY a JSON object with exactly these keys:
{"verdict":"pass|not_yet|unsure","whatYouGotRight":"","brokenStep":"","misconception":"","fluencyWarning":false,"hint":"","probeQuestion":"","walkthrough":"","freshGate":null,"juryFollowUp":""}
freshGate is either null or {"prompt":"","modelAnswer":""}.`;

function buildUserMessage(req: GradeRequest): string {
  const gate = req.activeGate;
  const ex = req.exercise;
  const lines = [
    `FEEDBACK LANGUAGE: ${req.lang === 'fr' ? 'French' : 'English'}`,
    `EXERCISE: ${gate ? gate.prompt : ex.prompt}`,
    `MODEL ANSWER (hidden from learner): ${gate ? gate.modelAnswer : ex.modelAnswer}`,
  ];
  if (!gate) {
    lines.push(`KEY POINTS:\n${ex.keyPoints.map((k, i) => `${i + 1}. ${k.point}`).join('\n')}`);
    lines.push(`AUTHORED HINTS:\nrung 1: ${ex.hints[0]}\nrung 2: ${ex.hints[1]}\nrung 3: ${ex.hints[2]}`);
    if (ex.misconceptions?.length) lines.push(`KNOWN MISCONCEPTIONS:\n- ${ex.misconceptions.join('\n- ')}`);
  } else {
    lines.push('This is a FRESH GATE generated after a walkthrough. Grade it the same way.');
  }
  if (req.previousAttempts.length) {
    lines.push(`EARLIER ATTEMPTS:\n${req.previousAttempts.map((a, i) => `#${i + 1}: ${a}`).join('\n')}`);
  }
  lines.push(`ATTEMPT NUMBER: ${req.attempt}`);
  lines.push(`CONFIDENCE (1-5): ${req.confidence}`);
  lines.push(`LEARNER ANSWER: ${req.answer}`);
  if (req.pushback) {
    lines.push(`PREVIOUS VERDICT: ${JSON.stringify(req.pushback.previousVerdict)}`);
    lines.push(`LEARNER PUSHBACK: ${req.pushback.argument}`);
  }
  return lines.join('\n\n');
}

async function callServer(system: string, user: string): Promise<string | null> {
  try {
    const res = await fetch('/api/coach', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ system, user }),
    });
    if (res.status === 503 || res.status === 404 || res.status === 405) return null;
    const data = await res.json().catch(() => ({}));
    if (!res.ok || typeof data.text !== 'string') throw new Error(data.error || `HTTP ${res.status}`);
    return data.text;
  } catch (e) {
    // Static hosting without the coach endpoint (e.g. `vite dev`) returns HTML, not JSON.
    if (e instanceof SyntaxError || (e instanceof TypeError && e.message.includes('fetch'))) return null;
    throw e;
  }
}

async function callBrowser(system: string, user: string): Promise<string | null> {
  const apiKey = getGeminiApiKey();
  if (!apiKey) return null;
  const body = JSON.stringify({
    systemInstruction: { parts: [{ text: system }] },
    contents: [{ role: 'user', parts: [{ text: user }] }],
    generationConfig: { temperature: 0.2, maxOutputTokens: 2048, responseMimeType: 'application/json' },
  });
  let lastError = 'unknown';
  for (const model of ['gemini-3.6-flash', 'gemini-2.5-flash']) {
    // Same request shape as geminiService.ts, which already works from the browser.
    const res = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(apiKey)}`,
      { method: 'POST', headers: { 'Content-Type': 'application/json' }, body }
    );
    if (res.ok) {
      const data = await res.json();
      const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
      if (text) return text;
      lastError = 'empty response';
    } else {
      const err = await res.json().catch(() => ({}));
      lastError = err?.error?.message || `HTTP ${res.status}`;
    }
  }
  throw new Error(lastError);
}

function parseVerdict(text: string): CoachVerdict {
  const start = text.indexOf('{');
  const end = text.lastIndexOf('}');
  const raw = JSON.parse(start >= 0 && end > start ? text.slice(start, end + 1) : text);
  const gate = raw.freshGate && typeof raw.freshGate.prompt === 'string' && raw.freshGate.prompt
    ? { prompt: String(raw.freshGate.prompt), modelAnswer: String(raw.freshGate.modelAnswer || '') }
    : null;
  const verdict = raw.verdict === 'pass' || raw.verdict === 'unsure' ? raw.verdict : 'not_yet';
  return {
    verdict,
    whatYouGotRight: String(raw.whatYouGotRight || ''),
    brokenStep: String(raw.brokenStep || ''),
    misconception: String(raw.misconception || ''),
    fluencyWarning: Boolean(raw.fluencyWarning),
    hint: String(raw.hint || ''),
    probeQuestion: String(raw.probeQuestion || ''),
    walkthrough: String(raw.walkthrough || ''),
    freshGate: gate,
    juryFollowUp: String(raw.juryFollowUp || ''),
    mode: 'llm',
  };
}

const normalize = (s: string) =>
  s.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '');

// Keyword check used when no LLM is reachable. It cannot judge reasoning, and says so.
function offlineGrade(req: GradeRequest): CoachVerdict {
  const ex = req.exercise;
  const text = normalize(req.answer);
  const covered = ex.keyPoints.filter((k) => k.keywords.some((w) => text.includes(normalize(w))));
  const missing = ex.keyPoints.filter((k) => !covered.includes(k));
  const pass = missing.length === 0 && req.answer.trim().length > 20;
  const fr = req.lang === 'fr';
  const rung = Math.min(req.attempt, 3) - 1;
  const reveal = !pass && req.attempt >= 4;
  return {
    verdict: pass ? 'pass' : 'not_yet',
    whatYouGotRight: covered.length
      ? (fr ? 'Points couverts : ' : 'Points you covered: ') + covered.map((k) => k.point).join(' · ')
      : '',
    brokenStep: pass ? '' : fr
      ? `${missing.length} point(s) clé(s) manquent encore dans ta réponse.`
      : `${missing.length} key point(s) are still missing from your answer.`,
    misconception: '',
    fluencyWarning: !pass && req.confidence >= 4,
    hint: pass || reveal ? '' : ex.hints[rung],
    probeQuestion: '',
    walkthrough: pass || reveal ? ex.modelAnswer : '',
    freshGate: null,
    juryFollowUp: '',
    mode: 'offline',
  };
}

export async function gradeAnswer(req: GradeRequest): Promise<CoachVerdict> {
  const user = buildUserMessage(req);
  let notice: string | undefined;
  let text: string | null = null;
  try {
    text = await callServer(SYSTEM_PROMPT, user);
  } catch (e) {
    // A misconfigured server key should not block studying: try the browser key, then offline.
    notice = `Server grader unavailable (${e instanceof Error ? e.message : String(e)}).`;
  }
  if (text === null) text = await callBrowser(SYSTEM_PROMPT, user);
  if (text === null) {
    if (req.activeGate) {
      throw new Error('The AI coach is not configured, so a generated fresh gate cannot be graded.');
    }
    return { ...offlineGrade(req), notice };
  }
  return { ...parseVerdict(text), notice };
}
